### PR TITLE
Fake clang update

### PR DESCRIPTION
**Pull request by bstaletic**
Rebased onto latest upstream master and added an option to customize the compiler for getting the system headers.

Rebase makes the PR not mergable.

---
This change is [Reviewable](https://reviewable.io/reviews/micbou/ycmd/4)

### CODE REVIEW

**Review by micbou — COMMENTED** [review]
Thanks. I am going to rebase the branch so that it's easier to review.

> *[Reviewable](https://reviewable.io/reviews/micbou/ycmd/4#-:-LPgj9h94LEFbDCiMYT3:b-96ggx9)* status: 0 of 154 files reviewed, all discussions resolved

**Review by bstaletic — COMMENTED** [review]
I rebased the PR, the changes can be applied cleanly now.

> *[Reviewable](https://reviewable.io/reviews/micbou/ycmd/4#-:-LPly4nq0-B99n7XQSw8:b8tp86d)* status: 0 of 2 files reviewed, all discussions resolved

**Review by bstaletic — COMMENTED** [review]
I pushed from the wrong clone. Test failures are fixed now.

> *[Reviewable](https://reviewable.io/reviews/micbou/ycmd/4#-:-LPp9Nnt6ZKnSnPldAKM:b-eutkzp)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by micbou** [comment]
See my comment in PR https://github.com/Valloric/ycmd/pull/853.

**Pull request closed without merging**
